### PR TITLE
Fix infobox bug

### LINKED ISSUE #368: Ignore NA in info box counts
We should ignore NA when populating the information box counts of specimens/individuals. While it would still signal something was wrong if this number was something unexpected due to NAs, since we get the unique values, this would still not give an indication of how many NAs. Instead it would just have one extra regardless of 1 NA or 100 NA.

Labeling as a bug since I don't think this is the desired behavior, but it's not technically a bug in the sense of being a breaking issue.

Based on feedback from Duminda.

### PR DESCRIPTION
**Pull request by Aryllen**
Fixes #368

Changes proposed in this pull request:

- Count individualID and specimenID differently. Instead of getting the number of strings returned from `unique()`, get a vector of `TRUE`/`FALSE` by asking if those strings are `!is.na()` and sum.

Please confirm you've done the following (if applicable):

- [x] Added tests for new functions or for new behavior in existing functions
- [ ] ~If adding a new exported function, added it to the reference section of `_pkgdown.yml`~
- [ ] ~If adding a new configuration option, documented it in `vignettes/customizing_dccvalidator.Rmd`~
- [x] If adding or changing functionality, documented it under "dccvalidator (development version)" in `NEWS.md`

### CODE REVIEW

File: R/app-server.R [hunk 1]
```diff
@@ -301,39 +301,33 @@ app_server <- function(input, output, session) {
...
     output$nindividuals <- renderValueBox({
       valueBox(
-        length(
-          unique(
-            c(
-              indiv()$individualID,
-              biosp()$individualID,
-              manifest()$individualID
-            )
+        sum(!is.na(unique(
```
Comment (karawoo) [inline R/app-server.R:304]: Since we repeat this calculation in several places, I wonder if it would make sense to write a small function, something like this: 

```r
count_unique_ids <- function(...) {
  sum(!is.na(unique(c(...))))
}
```

Comment (Aryllen) [reply R/app-server.R:304]: I had that same thought, but haven't tried it out just yet. I vaguely remember some issues popped up when I tried doing something like that in the dccmonitor app. I'll give it a whirl and see how it goes. I would much rather have a small, separate, testable function.

**Comment by Aryllen** [comment]
Added un-exported helper function `count_unique_values` in utils and a test for it. The counts boxes appear to be working nicely.  Using it for counting the IDs and the number of files in the manifest so made it slightly more generic named.

File: R/app-server.R [hunk 2]
```diff
@@ -301,14 +301,10 @@ app_server <- function(input, output, session) {
...
-            c(
-              indiv()$individualID,
-              biosp()$individualID,
-              manifest()$individualID
-            )
-          )
+        count_unique_values(
+          indiv()$individualID,
+          biosp()$individualID,
+          manifest()$individiualID
```
Comment (karawoo) [inline R/app-server.R:307]:
```suggestion
          manifest()$individualID
```

**Comment by Aryllen** [comment]
Nice catch, @karawoo. 🤦
